### ISSUE TITLE
undefined reference to `str2hex'

### ISSUE THREAD

**Issue by itshusky01** [Vandoul/tft_lcd_st7789_rtt#1]

**Comment by Zsh0225** [comment]
解决了嘛，我也遇到了这个问题

**Comment by Vandoul** [comment]
> 解决了嘛，我也遇到了这个问题

已增加str2hex函数

**Comment by Zsh0225** [comment]
您好，可以有偿帮我看一下我的tftlcd屏幕为啥在正点原子stm32f407上跑不起来嘛，已经确认屏幕是好的，然后在其他板子的例程上运行起来了的，这是我的qq  938730935
