### ISSUE TITLE
undefined reference to `spi_lcd_init'

### ISSUE THREAD

**Issue by Lyansun** [Vandoul/tft_lcd_st7789_rtt#3]
你好，调用初始化函数工具提示undefined reference to `spi_lcd_init'

**Comment by Lyansun** [comment]
RT-Thread Studio

版本: 2.2.8

**Comment by Vandoul** [comment]
> 你好，调用初始化函数工具提示undefined reference to `spi_lcd_init'

请阅读源码，spi_lcd_init是在lcd_st7789.c中实现的
